version = "1.2.0"

[class]
Microsoft-edge = "󰇩"
gnome-disks = "󰋊"
"[Gg]oogle-chrome" = ""
kitty = ""
Electron = ""
"[Ss]potify" = ""
Plex = "󰄙"
blueman-manager = "󰂱"
"[Ss]oftware" = "󱇕"
"org.gnome.Calendar" = ""
obsidian = ""
"[Ss]ignal" = ""
thunderbird-default = ""
Mailspring = "󰇮"
gnome-power-statistics = "⏼"
font-manager = ""
mailspring = "󰇮"
pavucontrol = "󱀞"
"org.mozilla.Thunderbird" = ""
transmission-remote-gtk = "󰦗"
mpv = "󰐌"
DEFAULT = "󰲋"
"org.gnome.Nautilus" = ""
"org.kde.okular" = ""
"org.pwmt.zathura" = ""
Spotify = ""
Bitwarden = ""
"[Ss]team" = ""
anki = "󱛊"
Discord = "󰙯"
firefox = ""
"[Aa]lacritty" = ""
"org.freecadweb.FreeCAD" = "󰻬"
zen = "󰺕"

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]

[title_in_class]

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"[Zz]en" = "[Pp]icture-in-[Pp]icture"
"" = "^$"
"[Ss]team" = "^$"
"[Ff]irefox" = "[Pp]icture-in-[Pp]icture"
"(?i)fcitx" = ".*"

[format]
dedup = true
dedup_inactive_fullscreen = true
delim = " "
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "[{icon}]"
client_active = "{icon}"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
